name: Release version

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_windows:
    name: Build Authenticator Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --manifest-path authenticator/Cargo.toml --release

      - name: Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ./authenticator/target/release/Authenticator.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux_x64:
    name: Build Authenticator Linux x64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Build release binary
        run:   cargo build  --target x86_64-unknown-linux-musl --manifest-path authenticator/Cargo.toml --release

      - name: Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ./authenticator/target/x86_64-unknown-linux-musl/release/Authenticator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}